### PR TITLE
[sc-28901] Validate query logs as they're parsed

### PR DESCRIPTION
**Pull request by usefulalgorithm**
### 🤔 Why?

We should validate the query logs as they're parsed, otherwise bugs are harder to find when they get to the lineage parser.

### 🤓 What?

Validate the parsed query logs before writing them to file.

Tested this against our own Snowflake instance (13,589 queries)
- No validation: ﻿36 secs
截圖 2024-09-23 中午12 53 10

- Validated: 1 min 37 secs
截圖 2024-09-23 中午12 51 24

### 🧪 Tested?

Tested against
- BigQuery
- Snowflake (see above)
- Unity Catalog

### ☑️ Checks

- [x] My PR contains actual code changes, and I have updated the version number in `pyproject.toml`.

### CODE REVIEW

**Review by elic-eon — COMMENTED** [review]
Didn't we validate them when ingestion?

**Comment by usefulalgorithm** [comment]
> Didn't we validate them when ingestion?

No, ingestion does not look at what's in the query log files.

**Comment by elic-eon** [comment]
> > Didn't we validate them when ingestion?
> 
> No, ingestion does not look at what's in the query log files.

Got it, can we also valid entities in the MCE as well? We encounter the MCE validation error when ingestion many times, if we can catch the error earlier, it is better.

**Comment by usefulalgorithm** [comment]
> > > Didn't we validate them when ingestion?
> > 
> > 
> > No, ingestion does not look at what's in the query log files.
> 
> Got it, can we also valid entities in the MCE as well? We encounter the MCE validation error when ingestion many times, if we can catch the error earlier, it is better.

MCEs are partially validated: https://github.com/MetaphorData/connectors/blob/main/metaphor/common/sink.py#L23C1-L28C14

It only validates against the json schema though, so it's kind of limited.

**Review by elic-eon — APPROVED** [review]

**Comment by usefulalgorithm** [comment]
@elic-eon  @mars-lan  let's not merge this, it takes too long, almost 2x the original time.

Without: 6 mins a batch
main

With: 14 mins a batch
with

**Pull request closed without merging**
