### PR TITLE
[sc-7255] Support Looker 4.x API

### PR DESCRIPTION
**Pull request by elic-eon**
### 🤔 Why?

Looker API 3.x has been deprecated.

### 🤓 What?

- Update `looker-sdk` to latest.
- Use `Looker40SDK` in order to use Looker API 4.0

### 🧪 Tested?

Ran connector locally

### CODE REVIEW

**Review by mars-lan — COMMENTED** [review]
Have you verified that the output stays identical?

**Comment by elic-eon** [comment]
> Have you verified that the output stays identical?

Just verified. Version 4.0 will have empty string if there is not description, and 3.x will have `None`. So new MCEs will have description field with empty string. Otherwise, it's identical.

**Comment by mars-lan** [comment]
> > Have you verified that the output stays identical?
> 
> Just verified. Version 4.0 will have empty string if there is not description, and 3.x will have `None`. So new MCEs will have description field with empty string. Otherwise, it's identical.

Got it. Please make sure the field is not annotated as `IsNotWhitespace` which won't accept empty strings.

**Comment by elic-eon** [comment]
> Got it. Please make sure the field is not annotated as IsNotWhitespace which won't accept empty strings.

Manually ingest the MCE successfully. And it in not annotated as IsNotWhitespace

**Review by mars-lan — APPROVED** [review]

**Pull request merged**
